### ISSUE TITLE
ODF ClassParent parameters are incorrectly parsed as ClassLabel

### ISSUE THREAD

**Issue by marth8880** [SleepKiller/swbf-unmunge#12]
For example, this:
```
[WeaponClass]

ClassLabel = "com_weap_inf_smg_n7hurricane"
GeometryName = "m9_tempest.msh"

[Properties]

HUDTag = "m9_tempest"
GeometryName = "m9_tempest"
HighResGeometry = "m9_tempest"
OrdnanceName = "ssv_weap_inf_smg_n7hurricane_ord"
```
should be this:
```
[WeaponClass]

ClassParent = "com_weap_inf_smg_n7hurricane"
GeometryName = "m9_tempest.msh"

[Properties]

HUDTag = "m9_tempest"
GeometryName = "m9_tempest"
HighResGeometry = "m9_tempest"
OrdnanceName = "ssv_weap_inf_smg_n7hurricane_ord"
```

**Comment by PrismaticFlower** [comment]
This is caused by both keys being turned into the same `BASE` [chunk](https://github.com/SleepKiller/swbf-unmunge/blob/f0ca81d98e522b7a1eb7f8ff3371148c10468874/src/handle_object.cpp#L73), which suggests from the game's point of view they're the same. However it would be easy to add a lookup table to check if we're dealing with a known `ClassLabel` and output the correct key name for the user's benefit.

**Comment by PrismaticFlower** [comment]
Turns out there is one key difference between `ClassLabel` and `ClassParent` and that is that the latter produces class references in `.req` files. So swbf-unmunge simply always using `ClassLabel` is actually a bug after all. If I (or someone else) ever work on swbf-unmunge again this would be a good and easy thing to fix.
